<?xml version="1.0"?>
<package format="3">
  <name>sar_perception</name>
  <version>0.0.1</version>
  <description>Drone perception node for SAR system</description>
  <maintainer email="you@email.com">Shaheer</maintainer>
  <license>MIT</license>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>px4_msgs</depend>
  <depend>sar_interfaces</depend>
  <buildtool_depend>ament_python</buildtool_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
